server.port: ${PORT:9999}

spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/orcl}
    username: ${DB_USERNAME:system}
    password: ${DB_PASSWORD:Kira12#$}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.Oracle12cDialect}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: ${SHOW_SQL:true}